spring:
  datasource:
    url: jdbc:postgresql://survey-master-pg-survey-master.e.aivencloud.com:25901/defaultdb?currentSchema=public
    username: survey-master
    password: ENC(38D4NPeXgGDNg4WT3oWTw3Gda8T+kgOdooTu+Y9la8kfCWYREX8DSSVQnshukJgiVDUsQIaS/A2f1h0i9RsGBw==)
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    location: static/banner/banner.txt
server:
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    password: ${SECRET_ENCRYPTION_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator