spring:
  datasource:
    url: jdbc:postgresql://survey-master-pg-survey-master.e.aivencloud.com:25901/defaultdb?currentSchema=public
    username: survey-master
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    location: banner/banner.txt
server:
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    password: ${SECRET_ENCRYPTION_KEY}